spring:
  ai:
    ollama:
      base-url: http://localhost:11435
      init:
        pull-model-strategy: when_missing
        chat:
          options:
            model: mistral
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        index-type: hnsw
  docker:
    compose:
      file: /Users/migueljorquera/IdeaProjects/SemanticSearch/docker-compose.yml
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5434/vectordb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081